app:
  api-prefix: ${API_PREFIX:/api/v1.0.0}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:http://identity-service:8080}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: profile-service
          uri: ${PROFILE_SERVICE_URI:http://profile-service:8081}
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URI:http://notification-service:8082}
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: post-service
          uri: ${POST_SERVICE_URI:http://post-service:8083}
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2

        - id: file-service
          uri: ${FILE_SERVICE_URI:http://file-service:8084}
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2
        - id: donation-service
          uri: ${DONATION_SERVICE_URI:http://localhost:8085}
          predicates:
            - Path=${app.api-prefix}/donation/**
          filters:
            - StripPrefix=2

springdoc:
  swagger-ui:
    urls:
      - name: Identity Service
        url: ${app.api-prefix}/identity/v3/api-docs
      - name: Profile Service
        url: ${app.api-prefix}/profile/v3/api-docs
      - name: File Service
        url: ${app.api-prefix}/file/v3/api-docs
      - name: Post Service
        url: ${app.api-prefix}/post/v3/api-docs
      - name: Donation Service
        url: ${app.api-prefix}/donation/v3/api-docs

server:
  port: ${SERVER_PORT:8888}

identity:
  url: ${IDENTITY_URL:http://identity-service:8080/identity}
