server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/post}

spring:
  application:
    name: post-service
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/post-service?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  service:
    file: ${FILE_SERVICE_URL:http://localhost:8084/file}
    profile: ${PROFILE_SERVICE_URL:http://localhost:8081/file}

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}

openapi:
  title: ${OPENAPI_TITLE:Charity Social Media Document}
  description: ${OPENAPI_DESCRIPTION:API documentation for Charity Social Media}
  version: ${OPENAPI_VERSION:1.0.0}
  license:
    name: ${OPENAPI_LICENSE_NAME:API License}
    url: ${OPENAPI_LICENSE_URL:https://www.facebook.com/nguyentuan.danh.167/}
  server:
    url: ${OPENAPI_SERVER_URL:http://localhost:8080/identity}
    description: ${OPENAPI_SERVER_DESCRIPTION:server test}