server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/file}

aws3:
  access_key: ${AWS_ACCESS_KEY}
  secret_key: ${AWS_SECRET_KEY}
  bucket_name: ${AWS_BUCKET_NAME}
  region: ${AWS_REGION:us-east-1}

jwt:
  signerKey: ${JWT_SIGNER_KEY}

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@mongo:27017/file-service?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9094}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.tuandanh.event.dto"

openapi:
  title: ${OPENAPI_TITLE:Charity Social Media Document}
  description: ${OPENAPI_DESCRIPTION:API documentation for Charity Social Media}
  version: ${OPENAPI_VERSION:1.0.0}
  license:
    name: ${OPENAPI_LICENSE_NAME:API License}
    url: ${OPENAPI_LICENSE_URL:https://www.facebook.com/nguyentuan.danh.167/}
  server:
    url: ${OPENAPI_SERVER_URL:http://identity-service:8080/identity}
    description: ${OPENAPI_SERVER_DESCRIPTION:server test}

