server:
  port: 8082
  servlet:
    context-path: /notification

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # tắt cache để testt
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.tuandanh.event.dto"

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
email:
  apiKey: ${EMAIL_API_KEY}

app:
  service:
    post: ${APP_SERVICE_POST:http://post-service:8083/post}
    profile: ${APP_SERVICE_PROFILE:http://profile-service:8081/profile}